// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDxNEWwMOf0-MMzyodT0VkljrvknorXBM',
    appId: '1:874913853948:android:4137d695f903936da74279',
    messagingSenderId: '874913853948',
    projectId: 'todo-app-c11-mon-106b7',
    storageBucket: 'todo-app-c11-mon-106b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA8QGnKqSv7b8bef2XWRj5-1r8Ezoaof8',
    appId: '1:874913853948:ios:94c5dc16adb6fb34a74279',
    messagingSenderId: '874913853948',
    projectId: 'todo-app-c11-mon-106b7',
    storageBucket: 'todo-app-c11-mon-106b7.appspot.com',
    iosBundleId: 'com.example.todoAppC11Mon',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2AkuNqC3-bFWkFCZQIWJRgUSSHkLOaCs',
    appId: '1:874913853948:web:018bb7cc804c180aa74279',
    messagingSenderId: '874913853948',
    projectId: 'todo-app-c11-mon-106b7',
    authDomain: 'todo-app-c11-mon-106b7.firebaseapp.com',
    storageBucket: 'todo-app-c11-mon-106b7.appspot.com',
    measurementId: 'G-FL652S05TL',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA8QGnKqSv7b8bef2XWRj5-1r8Ezoaof8',
    appId: '1:874913853948:ios:94c5dc16adb6fb34a74279',
    messagingSenderId: '874913853948',
    projectId: 'todo-app-c11-mon-106b7',
    storageBucket: 'todo-app-c11-mon-106b7.appspot.com',
    iosBundleId: 'com.example.todoAppC11Mon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2AkuNqC3-bFWkFCZQIWJRgUSSHkLOaCs',
    appId: '1:874913853948:web:26a632832e6ee6d6a74279',
    messagingSenderId: '874913853948',
    projectId: 'todo-app-c11-mon-106b7',
    authDomain: 'todo-app-c11-mon-106b7.firebaseapp.com',
    storageBucket: 'todo-app-c11-mon-106b7.appspot.com',
    measurementId: 'G-HZRPL91H9V',
  );
}
